### ISSUE TITLE
More precise calibration

### ISSUE THREAD

**Issue by v-iashin** [andyljones/coolgpus#3]
**Problem**
Let's assume I have two GPUs. I run my code on the first one (87C). The second one is idle (30C). 

I would like the first one to follow the rule `--temp 70 90  --speed  50 75`. 
On the second one: `--temp 10 70  --speed  20 20`. 

If I use the rule `--temp 70 90  --speed  50 75` I end up with the second GPU fan running 70% all the time despite being idle.

The more GPUs you have, the more annoying the problem becomes.

**Suggestion**
The idea is to create a piecewise function 
1. `sudo $(which coolgpus) --temp 10 69 70 90 --speed 20 20 50 75`
2. `sudo $(which coolgpus) --temp_gpu0 70 90 --speed_gpu0 50 75 --temp_gpu1 10 70 --speed_gpu1 20 20`

**Comment by andyljones** [comment]
I'd be happy to see (1) implemented since it'll preserve the existing behaviour. Want to fork the repo, put together something that suits your needs, and then PR it back when you're happy with it?

[Temperature control code is here](https://github.com/andyljones/coolgpus/blob/master/coolgpus#L169-L178). You'll want to alter  `min_speed`. For reference, that takes the current speed and temperature and returns a new min speed. You'll also need to adjust the `add_argument` calls to support a variable number of speed/temp args.

**Comment by andyljones** [comment]
Merged and distributed. Thanks again!
